WIP: use rpcLoopbackL instead of TCP listener in TestInternalSQL in order to make the test intentionally flaky. The test should pass most of the times; occasionally it will fail with,
E230816 17:04:40.385733 2114 1@server/server_sql.go:1811  [T1,n1,client=pipe] 140  serving SQL client conn: node is running secure mode, SSL connection required
server_special_test.go:133:
Error Trace: github.com/cockroachdb/cockroach/pkg/server/server_special_test.go:133
Error: Received unexpected error:
  failed to connect to `host=/tmp user=root database=`: server error (ERROR: node is running secure mode, SSL connection required (SQLSTATE 08P01))